### PR TITLE
Complete overhaul of install script

### PR DESCRIPTION
**Pull request by systeembeheeratabix**
Changes:
1. Homebrew now uses a Brewfile to install software in bulk
2. More clear code comments
3. Better readability because of newly added functions
4. Architecture detection
5. Better terminal environment
6. Easier debugging with steps being echoed
7. Developer & Non-developer option, functions also act as code de-duplication

### CODE REVIEW

**Comment by systeembeheeratabix** [comment]
Does anyone know if the wildcard certs in assets/certs are needed/referenced somewhere? If not, we should change the name to be compatible with windows, because you're not able to pull now.

**Comment by systeembeheeratabix** [comment]
Ah i see the references now, I'll open another PR for this.

**Comment by systeembeheeratabix** [comment]
As you can see, each file that's changed is a single commit, which is explained and fixed by #4

**Comment by brysem** [comment]
Hi Sacha,

LGTM. Love the changes!

**Pull request merged**
